# Base configs
baseurl: "http://www.aleckan.com/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography"
author: "Alec Kan"
header:
 title: "Photography"
 subtitle: "by Alec Kan"
